services:
  reverse-proxy:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
      - ./proxy/certs:/etc/nginx/certs
    networks:
      - marmon-net

  backend1:  # Nginx para /tienda
    image: nginx:alpine
    volumes:
      - ./backend1/html:/usr/share/nginx/html
      - ./backend1/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - marmon-net
    expose:
      - "8080"

  backend2:  # Python para /news
    image: python:alpine
    command: sh -c "cd /app && python -m http.server 9090"
    working_dir: /app
    volumes:
      - ./backend2/html:/app
    networks:
      - marmon-net
    expose:
      - "9090"

networks:
  marmon-net:
    driver: bridge