services:
  reverse-proxy:  # Servicio principal del proxy inverso
    image: nginx:alpine  # Imagen ligera de Nginx
    ports:
      - "80:80"    # Expone puerto HTTP (para redirección)
      - "443:443"  # Expone puerto HTTPS (tráfico principal)
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf  # Monta configuración personalizada
      - ./proxy/certs:/etc/nginx/certs  # Monta certificados SSL
    networks:
      - marmon-net  # Conecta a red interna

  backend1:  # Servicio backend para /tienda
    image: nginx:alpine  # Usa Nginx para servir contenido
    volumes:
      - ./backend1/html:/usr/share/nginx/html  # Monta contenido web
      - ./backend1/nginx.conf:/etc/nginx/conf.d/default.conf  # Configuración
    networks:
      - marmon-net  # Misma red interna
    expose:
      - "8080"  # Expone puerto solo internamente

  backend2:  # Servicio backend para /news
    image: python:alpine  # Usa servidor Python simple
    command: sh -c "cd /app && python -m http.server 9090"  # Comando de inicio
    working_dir: /app  # Directorio de trabajo
    volumes:
      - ./backend2/html:/app  # Monta contenido web
    networks:
      - marmon-net  # Misma red interna
    expose:
      - "9090"  # Expone puerto solo internamente

networks:
  marmon-net:  # Red aislada para comunicación segura
    driver: bridge  # Tipo de red (conexión entre contenedores)